# Generated by Django 4.2.3 on 2023-07-20 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Photo',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='title',
            new_name='keyword',
        ),
    ]
